print('=====DESAFIO 1=====')
nome = input('Qual é o seu nome?')
print('Olá', nome,'prazer em te conhecer!')
print('=====DESAFIO 2=====')
dia = input('Qual é o dia em que você nasceu?')
mes = input('Qual é o mês que você nasceu?')
ano = input('Qual é o ano em que você nasceu?')
print('Você nasceu no dia',dia,'de',mes,'de',ano,'. Correto?')
print('=====DESAFIO 3=====')
num1 = input('Digite um numero:')
num2 = input('Digite outro numero:')
soma = int(num1)+int(num2)
print('A soma é:',soma)
